name: Notify GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PAGES_DEPLOY }}" \
               --data '{"event_type": "update_readme"}' \
               https://api.github.com/repos/cdkooistra/cdkooistra.github.io/dispatches
